### PR TITLE
Successfully added Backend by using node and express ,added server.js…

### PR DESCRIPTION
**Pull request by Amadabh**
Added backend functionality. The hello world is shown at the bottom of the page

### CODE REVIEW

**Comment by adityabisoi** [comment]
Good work,! Can you please change the URI's in `package.json` to this upstream project URI? It'll be good to go then.

**Comment by Amadabh** [comment]
> Good work,! Can you please change the URI's in `package.json` to this upstream project URI? It'll be good to go then.

should I change the URL to this https://github.com/adityabisoi/startup-incubator/

**Comment by adityabisoi** [comment]
Yes.

**Comment by Amadabh** [comment]
How is it now

**Comment by adityabisoi** [comment]
LGTM

**Pull request merged**
