### PR TITLE
Folder structure,frontend with material UI,redux implementation, like, comment with beckend.

### PR DESCRIPTION
**Pull request by Anirudh4656**
Key feature of my work.
1. Improved folder structure
2. created beckend for posting of product, implemented like feature ,comment feature with data stored in mongodb.
3. .Implemented redux for state mangement, used axios to fetch data from beckend.

I am contributing for first time ,please overview if there is need of correction.

### CODE REVIEW

**Comment by adityabisoi** [comment]
Please create an issue first. Also, can you send screenshots of your page

**Comment by Anirudh4656** [comment]
> Please create an issue first. Also, can you send screenshots of your page

IMG_20220313_113625
IMG_20220313_113611
IMG_20220313_113559
IMG_20220313_113551

**Comment by adityabisoi** [comment]
Please resolve the conflicts.

**Comment by adityabisoi** [comment]
Please resolve conflicts.

**Comment by Anirudh4656** [comment]
@adityabisoi  please tell how can I solve this error

**Comment by adityabisoi** [comment]
You have to pull latest changes, resolve conflicts and push again. https://stackoverflow.com/questions/161813/how-to-resolve-merge-conflicts-in-a-git-repository

**Comment by adityabisoi** [comment]
Closing due to inactivity

**Pull request closed without merging**
