### PR TITLE
Removed package-lock.json and added buttons

### PR DESCRIPTION
**Pull request by ayush25102001**
For issue #32

### CODE REVIEW

**Comment by ayush25102001** [comment]
Please review @adityabisoi

**Comment by adityabisoi** [comment]
This PR has the file too. Please double check.

**Comment by ayush25102001** [comment]
> This PR has the file too. Please double check.

which file ??

**Comment by adityabisoi** [comment]
> > This PR has the file too. Please double check.
> 
> which file ??

client/package-lock.json which has been deleted.

**Comment by ayush25102001** [comment]
> > > This PR has the file too. Please double check.
> > 
> > 
> > which file ??
> 
> client/package-lock.json which has been deleted.

Sir, I have a doubt I have PM u on discord can u please see it

**Pull request closed without merging**
