### PR TITLE
Added About-Us Page 

### LINKED ISSUE #33: Add a AboutUs Component
Hi mentor I am a Gssoc'22 Contributor.
I want to add a **About Us** page to this repository.

Project Description
The project will contain a modern ui design and the contents you want to display about the team behind the website, social handles and other information.
This will help new developers to understand ui/ux designing and frontend. 

Tech Stack Used 
- Javascript
- Tailwindcss
- Framer motion

### PR DESCRIPTION
**Pull request by shelabh**
Hi mentor,
I have added _**About-Us Page**_ to the website, here are the previews 

Screenshot 2022-03-08 at 2 31 24 AM

<br />
Screenshot 2022-03-08 at 2 34 14 AM

Kindly review the changes. 

fixes #33

### CODE REVIEW

**Review by pranav2012 — CHANGES_REQUESTED** [review]
hey, try to improve the ui and use tailwind completely

**Comment by shelabh** [comment]
@pranav2012 okay sure

**Comment by adityabisoi** [comment]
@shelabh Your status?

**Comment by shelabh** [comment]
@adityabisoi hey, i'll be pushing the code tomorrow im almost done

**Comment by pranav2012** [comment]
> @adityabisoi hey, i'll be pushing the code tomorrow im almost done

any updates?

**Comment by adityabisoi** [comment]
Closing due to inactivity

**Pull request closed without merging**
