### PR TITLE
userModelisAdded

### PR DESCRIPTION
**Pull request by ayush25102001**
Added the user Model with fields like name, email, password.
Used the validator package for email and password field.
Used mongoose package to make use of mongoose model.
PR with respect to issue #50

### CODE REVIEW

**Comment by ayush25102001** [comment]
Please review @rohan-kulkarni-25

**Comment by ayush25102001** [comment]
@pranav2012 please review

**Comment by adityabisoi** [comment]
You can continue with your contributions, your PR shall be reviewed.

**Review by pranav2012 — CHANGES_REQUESTED** [review]
add linting and you just added the schema where are you using this??

**Comment by ayush25102001** [comment]
@pranav2012  for issue #14 I require schema

**Comment by pranav2012** [comment]
> @pranav2012 for issue #14 I require schema

Okay, format your code everything else LGTM!

**Comment by ayush25102001** [comment]
@pranav2012 sir , I installed eslint

**Review by pranav2012 — APPROVED** [review]

**Comment by ayush25102001** [comment]
@pranav2012 sir can u merge this I require this for issue #14

**Comment by pranav2012** [comment]
> @pranav2012 sir can u merge this I require this for issue #14

@adityabisoi will merge it after final review

**Pull request merged**
