### PR TITLE
AddedUserModel

### PR DESCRIPTION
**Pull request by ayush25102001**
Added the user Model with fields like name, email, password.
Used the validator package for email and password field.
Used mongoose package to make use of mongoose model.
PR with respect to issue #50

### CODE REVIEW

**Comment by adityabisoi** [comment]
Why is a new folder created inside client?

**Comment by ayush25102001** [comment]
> Why is a new folder created inside client?

I created a folder named backend inside client so that all server side folders and files concerned with the backend are inside one folder.
This makes the code more modular and it will be easy if we add new routes/features in the backend.

**Comment by ayush25102001** [comment]
> Why is a new folder created inside client
Ig I need to remove that folder of backend outside client ??

**Comment by adityabisoi** [comment]
Yes, but the package.json you see in the root folder can be used for backend.

**Comment by ayush25102001** [comment]
> Yes, but the package.json you see in the root folder can be used for backend.

Can u tell me what modifications should I make ??

**Comment by ayush25102001** [comment]
> Yes, but the package.json you see in the root folder can be used for backend.

Done !!

**Comment by adityabisoi** [comment]
Again, the problem with the package-lock.json. You should not delete it, instead be sure not to commit it.

**Comment by adityabisoi** [comment]
> > Yes, but the package.json you see in the root folder can be used for backend.
> 
> Can u tell me what modifications should I make ??

I meant, we can use the root directory to have backend code.

**Pull request closed without merging**
