### PR TITLE
Cards added in homepage

### LINKED ISSUE #73: Bug report: making the products in card format !
We can change the UI of the products view in the homepage.
We can display them in the card format as shown below.
It looks stunning !

I will be doing it using semantic-ui which has been originally used in the project.
**Screenshot**

**Additional details**
I am contributor at GSSOC'22.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Siddhesh777**
Closes #73 

Added cards while displaying all the products inside homepage.

### CODE REVIEW

**Comment by Siddhesh777** [comment]
hey @adityabisoi Please review this PR

**Comment by Siddhesh777** [comment]
hey @pranav2012 
Can you please review this PR ?
I wanna raise some more issues which are related to this PR.

**Review by pranav2012 — APPROVED** [review]
LGTM

**Comment by Siddhesh777** [comment]
hey @adityabisoi Please review this PR

**Comment by adityabisoi** [comment]
@Siddhesh777 You don't have to mention more than once. Your PR(s) will be reviewed and merged, you can continue with your contributions

**Comment by Siddhesh777** [comment]
hey @adityabisoi 
Can you please add labels?

**Pull request merged**
