### PR TITLE
Added table of contents

### PR DESCRIPTION
**Pull request by artimanputra**
@adityabisoi, @subhangi2731 Added Table of contents in the readme file.

### CODE REVIEW

**Comment by subhangi2731** [comment]
@artimanputra Have you provided the complete contents?

**Comment by subhangi2731** [comment]
@artimanputra please provide the complete setup instructions and describe every content

**Comment by adityabisoi** [comment]
@subhangi2731 Let's cover that in another issue.

**Comment by subhangi2731** [comment]
@adityabisoi was this one only for topics?

**Comment by adityabisoi** [comment]
Yes

**Pull request merged**
