### PR TITLE
Navbar and UI changed

### PR DESCRIPTION
**Pull request by arzitmahajan**
Customized more attractive and interactive navbar along with change in background of dummy products

### CODE REVIEW

**Comment by arzitmahajan** [comment]
Please mark appropriate labels for this PR (GSSOC)

**Comment by adityabisoi** [comment]
@arzitmahajan Can you please link your issue here

**Comment by arzitmahajan** [comment]
> @arzitmahajan Can you please link your issue here

#65 is the issue number (https://github.com/adityabisoi/startup-incubator/issues/65)

**Comment by adityabisoi** [comment]
Please post some screenshots of the final work here.

**Comment by arzitmahajan** [comment]
image
image
image

Note: The top bar font is animated it keeps on changing its size

**Comment by arzitmahajan** [comment]
@adityabisoi @pranav2012 please review this

**Comment by adityabisoi** [comment]
Great work with the UI! Just a few caveats, after which this will be good for merging:
* Resolve conflicts
* Change the purple-pink theme to something light blue and nice such as [this](https://www.schemecolor.com/light-blue-gradient-color-scheme.php)
* Make this icon background white in navbar

**Comment by arzitmahajan** [comment]
Okay sir will implement the changes by tonight.
One more thing I don't know in my every PR the lock file automatically get deleted can you guide me how to resolve this?

**Comment by adityabisoi** [comment]
If you're talking about `package-lock.json`, it won't get deleted unless you delete it from the PR.

**Comment by arzitmahajan** [comment]
But it happened in another project also and was very difficult to resolve then the last thing that worked was pasting the whole lock file after copying from main branch file

**Comment by arzitmahajan** [comment]
@adityabisoi 
What about this theme?
image

(And another thing the navbar is scrollable i.e when user scroll up  through page it automatically hide itself and came back when user scroll down

**Comment by arzitmahajan** [comment]
Another color combination
image

image

**Comment by adityabisoi** [comment]
> @adityabisoi What about this theme? image
> 
> (And another thing the navbar is scrollable i.e when user scroll up through page it automatically hide itself and came back when user scroll down

This looks better.

**Comment by arzitmahajan** [comment]
And what should be the color of buttons while hovering over them?

**Comment by adityabisoi** [comment]
White would look great.

**Comment by arzitmahajan** [comment]
Please review now i have resolved the conflicts and made the changes

**Comment by adityabisoi** [comment]
This file shows conflict `client/package-lock.json`

**Comment by arzitmahajan** [comment]
how to resolve this error please guide me I edited the lock files by pasting the file from main branch any other way to recover the lock files

**Comment by adityabisoi** [comment]
You can try deleting the file from client/ and pasting the original from main branch. If nothing works, try doing a fresh clone and making a PR.

**Comment by arzitmahajan** [comment]
okay sir

**Comment by arzitmahajan** [comment]
please check now

**Comment by adityabisoi** [comment]
Nice work!

**Comment by arzitmahajan** [comment]
Thank you

**Pull request merged**
