### PR TITLE
ConnectionMade 

### PR DESCRIPTION
**Pull request by ayush25102001**
Previously the user entries on signUp were not going into the database which is not the case now.
React frontend(PORT3000) connected with express backend(PORT 5000)
User registers -> credentials go into the Db
User login -> credentials are verified from the Db

Register User:
db 1

Entry created in Db:
db 2

Login:
db 3

### CODE REVIEW

**Comment by ayush25102001** [comment]
Please review @pranav2012 @adityabisoi

**Comment by ayush25102001** [comment]
@pranav2012 sir please review

**Review by pranav2012 — APPROVED** [review]
LGTM

**Comment by adityabisoi** [comment]
@ayush25102001 Please resolve conflicts

**Comment by ayush25102001** [comment]
> @ayush25102001 Please resolve conflicts

Created a new PR

**Comment by pranav2012** [comment]
> > @ayush25102001 Please resolve conflicts
> 
> Created a new PR

don't change package-lock.json it will be resolved just pull from the repo

**Comment by ayush25102001** [comment]
> > > @ayush25102001 Please resolve conflicts
> > 
> > 
> > Created a new PR
> 
> don't change package-lock.json it will be resolved just pull from the repo

sir but I made a new PR now

**Pull request merged**
