### PR TITLE
Login/SignOut button

### PR DESCRIPTION
**Pull request by ayush25102001**
#32 
BEFORE:

AFTER:
final

### CODE REVIEW

**Review by pranav2012 — APPROVED** [review]

**Comment by pranav2012** [comment]
LGTM !

**Comment by adityabisoi** [comment]
please remove package-lock.json from your commit.

**Comment by adityabisoi** [comment]
Please remove the package-lock.json file, so I can merge the PR

**Comment by ayush25102001** [comment]
> Please remove the package-lock.json file, so I can merge the PR

Yes sir, I will do it till tomorrow actually I was travelling to college.

**Pull request closed without merging**
