### PR TITLE
Scroll Button position and UI corrected

### LINKED ISSUE #94: Bug report : Scroll to top button position should be fixed
**Describe the bug**
The scroll to top button inside homepage has its position at the bottom of the page, So if user want to come to the top of the page then the user first need to come to the bottom of the page which make no sense. Rather the position of the  button should be fixed so that user can click whenever required.

Also the UI of the button needs improvement.

**Screenshots**

**Additional details**
I am contributor at gssoc'22.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Siddhesh777**
Closes #94 
Made the correction in Position and UI of ScrollToTop button .

### CODE REVIEW

**Comment by Siddhesh777** [comment]
hey @adityabisoi 
Please review this PR

**Comment by Siddhesh777** [comment]
hey @pranav2012 
Please review this PR

**Review by pranav2012 — COMMENTED** [review]
generally it should be on the right side your screenshot shows it on the left side why?

**Comment by Siddhesh777** [comment]
@pranav2012 
Should I take it to left side?

**Comment by Siddhesh777** [comment]
hey @pranav2012 
Made it to the right side.

**Comment by adityabisoi** [comment]
LGTM now

**Pull request merged**
