### PR TITLE
added home page

### PR DESCRIPTION
**Pull request by sreechand2002**
ss1

### CODE REVIEW

**Comment by adityabisoi** [comment]
@sreechand2002 Add screenshots as well.

**Comment by sreechand2002** [comment]
should i put the screenshots in a separate folder ?

**Comment by adityabisoi** [comment]
@sreechand2002 Add screenshots in the descriptions of this PR so that I can review it.

**Comment by sreechand2002** [comment]
ss1

**Comment by adityabisoi** [comment]
@sreechand2002 Decrease the width of the header and make it visible, i.e., change its color. It would also be good to present a nice background and proper color combinations across the homepage.

**Comment by sreechand2002** [comment]
please review the changes

**Comment by adityabisoi** [comment]
@sreechand2002 It seems you haven't added the images folder. Please add it.

**Comment by sreechand2002** [comment]
There is a images folder inside the public folder of the client

**Comment by adityabisoi** [comment]
@sreechand2002 The images are not showing on the website. Maybe because of wrong path.

**Comment by sreechand2002** [comment]
> @sreechand2002 The images are not showing on the website. Maybe because of wrong path.
i can see the images on my local system and i have given a relative path , in the screenshot you can see all the images are appearing fine

**Comment by adityabisoi** [comment]
Correct your naming. You have used `Images` instead of `images` as foldername.

**Comment by sreechand2002** [comment]
You can check it out now

**Pull request merged**
